// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;

namespace DevSkills.Models;

public class DevSkillsDBContext : DbContext
{
    public DevSkillsDBContext(DbContextOptions<DevSkillsDBContext> options)
        : base(options)
    {
    }

    public DbSet<Desenvolvedor> Desenvolvedor { get; set; }

    public DbSet<Skills> Skills { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Desenvolvedor>(entity =>
        {
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Email).HasMaxLength(255);
            entity.Property(e => e.Nome).HasMaxLength(255);
        });

        modelBuilder.Entity<Skills>(entity =>
        {
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Nome).HasMaxLength(255);
            entity.HasOne(e => e.Desenvolvedor).WithMany().HasForeignKey(e => e.DesenvolvedorId);
        });
    }

}