// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace DevSkills.Models;

public class Desenvolvedor
{
    public virtual int Id { get; set; }

    public virtual string Nome { get; set; }

    public virtual string Email { get; set; }

}