// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace DevSkills.Models;

public class Skills
{
    public virtual int Id { get; set; }

    public virtual string Nome { get; set; }
    
    public virtual Desenvolvedor Desenvolvedor {get; set;}

    public virtual int DesenvolvedorId {get; set;}
}